### ISSUE TITLE
doesnt bypasses anything

### ISSUE THREAD

**Issue by JacqueSatan** [zkcm1337/Discord-rate-limit-bypass#2] opened 2020-04-21 23:03 UTC
its in the title

**Comment by zkcm1337** [comment] 2020-04-22 07:18
duplicate of #1 i suggest you to read it.

**Closed by zkcm1337** 2020-04-22 07:18 UTC

**Comment by JacqueSatan** [comment] 2020-04-23 18:29
discord.js "bypasses" the rate limit automatically then

**Comment by zkcm1337** [comment] 2020-04-24 08:37
you will still get rate limited if you to many events at a certain time for eg dmall

**Comment by JacqueSatan** [comment] 2020-04-24 15:21
well your method is very inefficient, you should just catch the rate limit exception and make your program wait for the given amount of time

**Comment by zkcm1337** [comment] 2020-04-24 15:46
its a simple code, you can modify it however you want, im not making everything from front to back because people need to figure somethings out them selfs
